// SPDX-License-Identifier: MIT

package installer

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/adamtait/reviewer/internal/config"
	"github.com/adamtait/reviewer/internal/testfixture"
)

const releaseV = "v0.1.0"

func TestInstallWritesTheFileSetAndIsIdempotent(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	git := testfixture.Git(t, root)

	first := install(t, root)
	if len(first.Created) != 7 || len(first.Overwritten) != 0 || len(first.Unchanged) != 0 {
		t.Fatalf("want seven files created, got %+v", first)
	}
	// git collapses new directories, so the seven files show as three untracked
	// entries: .agent/, .github/ and .review/. Anything else is a path the plan did
	// not name, which is the guarantee --dry-run rests on.
	if status := strings.Fields(git("status", "--porcelain")); len(status) != 6 {
		t.Errorf("want exactly .agent/, .github/ and .review/ untracked, got:\n%s",
			git("status", "--porcelain"))
	}

	second := install(t, root)
	if len(second.Created) != 0 || len(second.Unchanged) != 7 {
		t.Errorf("a second install must change nothing, got %+v", second)
	}
	if len(second.Manual) == 0 {
		// The devDependency step is still outstanding on a re-run: the installer
		// does not write it, so it cannot know it has been done.
		t.Error("want the outstanding manual steps repeated")
	}
}

// The generated config has to satisfy the loader that will read it, including
// its rejection of unknown keys. A template that drifts from the schema produces
// an install that only fails on the first real review.
func TestTheGeneratedConfigLoadsAndValidates(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	install(t, root)

	cfg, _, err := config.Resolve(root, "", func(string) string { return "" })
	if err != nil {
		t.Fatalf("the generated config does not load: %v", err)
	}
	if err := cfg.Validate(); err != nil {
		t.Fatalf("the generated config does not validate: %v", err)
	}

	if len(cfg.Plugins) != 1 || cfg.Plugins[0].ID != "typescript" {
		t.Fatalf("want the TypeScript plugin configured, got %+v", cfg.Plugins)
	}
	// dist/main.js is the executable; dist/serve.js is the library the package's
	// "main" field names. Pointing at the library gives a process that exits 0
	// without answering the handshake, and a review that reports no analyzers.
	if got := strings.Join(cfg.Plugins[0].Args, " "); !strings.HasSuffix(got, "/dist/main.js") {
		t.Errorf("want the plugin's executable entry point, got %q", got)
	}
	if cfg.LaneB.Enabled {
		t.Error("the model lane must be off in every generated config")
	}
	if cfg.GitHub.ResolveStaleThreads {
		t.Error("resolving a human's thread must be opt-in")
	}
}

func TestTheGeneratedConfigForARepositoryWithoutTypeScript(t *testing.T) {
	root := t.TempDir()
	write(t, root, "package.json", `{"name":"plain"}`)
	testfixture.Git(t, root)("init", "-q", "-b", "main")

	report := install(t, root)
	if len(report.Created) != 7 {
		t.Fatalf("want the full file set regardless, got %+v", report)
	}
	cfg, _, err := config.Resolve(root, "", func(string) string { return "" })
	if err != nil {
		t.Fatalf("the generated config does not load: %v", err)
	}
	if len(cfg.Plugins) != 0 {
		t.Errorf("nothing TypeScript-shaped was detected; got %+v", cfg.Plugins)
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("a plugin-less config must still be valid: %v", err)
	}
	if len(report.Manual) == 0 || strings.Contains(strings.Join(report.Manual, " "), PluginPackage) {
		t.Errorf("want no plugin install step, got %v", report.Manual)
	}
}

func TestForceReplacesAnExistingFile(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	write(t, root, ".review/config.yaml", "plugins: []\n")

	plan := BuildPlan(mustDetect(t, root), releaseV, Options{Force: true})
	report, err := Install(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Overwritten) != 1 || report.Overwritten[0] != ".review/config.yaml" {
		t.Fatalf("want exactly the one existing file replaced, got %+v", report)
	}
	body := read(t, root, ".review/config.yaml")
	if !strings.Contains(body, "Generated by `reviewer init`") {
		t.Error("want the file actually replaced")
	}
}

func TestWithoutForceAnExistingFileIsUntouched(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	write(t, root, ".review/config.yaml", "# mine\nplugins: []\n")

	report := install(t, root)
	if len(report.Unchanged) != 1 {
		t.Fatalf("want the existing file left alone, got %+v", report)
	}
	if body := read(t, root, ".review/config.yaml"); body != "# mine\nplugins: []\n" {
		t.Errorf("the file was modified: %q", body)
	}
}

// The installer must be incapable of persisting a credential. This is a property
// of the templates, so it is asserted against what was actually written rather
// than against the code that writes it.
func TestNothingWrittenLooksLikeACredential(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	report := install(t, root)

	// Any assignment with a non-empty right-hand side in .env.example, plus the
	// key prefixes the providers use.
	assigned := regexp.MustCompile(`(?m)^[A-Z_]+=\S`)
	secretish := regexp.MustCompile(`(sk-|ghp_|github_pat_|gsk_|AIza|xoxb-)`)

	for _, path := range report.Created {
		body := read(t, root, path)
		if path == ".review/.env.example" && assigned.MatchString(body) {
			t.Errorf(".env.example assigns a value:\n%s", body)
		}
		if secretish.MatchString(body) {
			t.Errorf("%s contains something credential-shaped:\n%s", path, body)
		}
	}
}

func TestTheGeneratedWorkflowUsesTheDetectedPackageManager(t *testing.T) {
	for _, tc := range []struct {
		lockfile string
		want     []string
		absent   []string
	}{
		{
			lockfile: "package-lock.json",
			want:     []string{`cache: "npm"`, `run: "npm ci"`},
			absent:   []string{"corepack"},
		},
		{
			// corepack, before setup-node: pnpm is not on a hosted runner, and
			// setup-node's cache resolution shells out to `pnpm store path`.
			lockfile: "pnpm-lock.yaml",
			want:     []string{"- run: corepack enable", `cache: "pnpm"`, `run: "pnpm install --frozen-lockfile"`},
		},
		{
			lockfile: "yarn.lock",
			want:     []string{"- run: corepack enable", `cache: "yarn"`, `run: "yarn install --immutable"`},
		},
		{
			// actions/setup-node accepts npm, yarn and pnpm only. `cache: bun`
			// fails the step outright, so bun gets no cache and a manual step.
			lockfile: "bun.lockb",
			want:     []string{`run: "bun install --frozen-lockfile"`},
			absent:   []string{"cache:"},
		},
	} {
		t.Run(tc.lockfile, func(t *testing.T) {
			root := t.TempDir()
			write(t, root, "package.json", `{"name":"x","devDependencies":{"typescript":"^5"}}`)
			write(t, root, "tsconfig.json", `{}`)
			write(t, root, tc.lockfile, "")

			report := install(t, root)
			body := read(t, root, ".github/workflows/review.yml")
			for _, want := range tc.want {
				if !strings.Contains(body, want) {
					t.Errorf("want %q in the workflow:\n%s", want, body)
				}
			}
			for _, absent := range tc.absent {
				if strings.Contains(body, absent) {
					t.Errorf("want no %q in the workflow:\n%s", absent, body)
				}
			}
			if tc.lockfile == "bun.lockb" && !strings.Contains(strings.Join(report.Manual, "\n"), "installing bun") {
				t.Errorf("want the missing bun named as an outstanding step, got %v", report.Manual)
			}
		})
	}
}

// A workflow generated by a release pins that release. One generated by a
// development build cannot, because there is no release archive to download, so it
// carries an obvious placeholder and says so as an outstanding step.
func TestTheGeneratedWorkflowPinsAReleaseOrSaysItCannot(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	plan := BuildPlan(mustDetect(t, root), releaseV, Options{})
	if _, err := Install(plan, releaseV); err != nil {
		t.Fatal(err)
	}
	if body := read(t, root, ".github/workflows/review.yml"); !strings.Contains(body, "adamtait/reviewer@v0.1.0\n") {
		t.Errorf("want the release pinned:\n%s", body)
	}

	dev := testfixture.Destination(t, "tiny-monorepo")
	devPlan := BuildPlan(mustDetect(t, dev), "dev", Options{})
	report, err := Install(devPlan, "dev")
	if err != nil {
		t.Fatal(err)
	}
	body := read(t, dev, ".github/workflows/review.yml")
	if !strings.Contains(body, versionPlaceholder) {
		t.Errorf("want an obvious placeholder, not @vdev:\n%s", body)
	}
	if !strings.Contains(strings.Join(report.Manual, "\n"), versionPlaceholder) {
		t.Errorf("want the placeholder named as an outstanding step, got %v", report.Manual)
	}
}

func TestInstallCommandFollowsThePackageManager(t *testing.T) {
	d := Dependency{Name: PluginPackage, Version: "0.1.0"}
	for manager, want := range map[string]string{
		"npm":     "npm install --save-dev",
		"pnpm":    "pnpm add -Dw",
		"yarn":    "yarn add -D",
		"bun":     "bun add -d",
		"":        "npm install --save-dev",
		"nonsuch": "npm install --save-dev",
	} {
		if got := installCommand(manager, d); !strings.HasPrefix(got, want) {
			t.Errorf("installCommand(%q) = %q, want it to start with %q", manager, got, want)
		}
	}
}

// Render produces content for exactly the files the plan names. A writer that can
// invent a path makes --dry-run's file list a guess.
func TestRenderProducesOnlyPlannedFiles(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	plan := BuildPlan(mustDetect(t, root), releaseV, Options{})

	files, err := Render(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	planned := map[string]bool{}
	for _, f := range plan.Files {
		planned[f.Path] = true
	}
	for _, f := range files {
		if !planned[f.Path] {
			t.Errorf("rendered %s, which the plan does not name", f.Path)
		}
	}
	if len(files) != len(plan.Files) {
		t.Errorf("rendered %d files for a plan of %d", len(files), len(plan.Files))
	}
}

func install(t *testing.T, root string) Report {
	t.Helper()
	plan := BuildPlan(mustDetect(t, root), releaseV, Options{})
	report, err := Install(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	return report
}

func read(t *testing.T, root, path string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		t.Fatal(err)
	}
	return string(body)
}

// A repository can commit a symlink at any component of a path this installer
// writes. Following it would put bytes outside the root while the report named an
// in-repo path — an escape and a false statement about where the bytes went.
func TestInstallRefusesToWriteThroughASymlink(t *testing.T) {
	for _, tc := range []struct{ name, link, target string }{
		{name: "a directory component", link: ".review", target: "../outside"},
		{name: "the file itself", link: ".review/.env.example", target: "../../outside/taken.txt"},
		// The dangerous case: a dangling link looks absent to a plain Stat, so it
		// would be planned as "create" and then create the target.
		{name: "a dangling link", link: ".github", target: "../outside/nothing-here"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			base := t.TempDir()
			root := filepath.Join(base, "repo")
			outside := filepath.Join(base, "outside")
			for _, dir := range []string{root, outside} {
				if err := os.MkdirAll(dir, 0o755); err != nil {
					t.Fatal(err)
				}
			}
			write(t, root, "package.json", `{"name":"x"}`)
			link := filepath.Join(root, filepath.FromSlash(tc.link))
			if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(tc.target, link); err != nil {
				t.Fatal(err)
			}

			plan := BuildPlan(mustDetect(t, root), releaseV, Options{})
			if len(plan.Problems) == 0 {
				t.Fatal("want the symlink reported as a problem")
			}
			if _, err := Install(plan, releaseV); err == nil {
				t.Fatal("want the install refused")
			}
			entries, err := os.ReadDir(outside)
			if err != nil {
				t.Fatal(err)
			}
			if len(entries) != 0 {
				t.Errorf("the install wrote outside the root: %v", entries)
			}
		})
	}
}

// `.review` present as a regular file makes every path under it fail with ENOTDIR.
// Classing those as "unchanged" turns an install that wrote no config at all into
// one that reports success.
func TestInstallRefusesAPathItCannotExamine(t *testing.T) {
	root := t.TempDir()
	write(t, root, "package.json", `{"name":"x"}`)
	write(t, root, ".review", "not a directory\n")

	plan := BuildPlan(mustDetect(t, root), releaseV, Options{})
	// Two distinct causes: `.review` is not a directory, and neither is
	// `.review/rules`. Four blocked paths must not become four problems.
	if len(plan.Problems) != 2 {
		t.Fatalf("want the problems deduplicated by cause, got %v", plan.Problems)
	}
	if _, err := Install(plan, releaseV); err == nil {
		t.Fatal("want the install refused rather than reported as unchanged")
	}
}

// The plan and the report must not disagree about outstanding work: two of these
// steps decide whether the generated workflow runs at all, so a dry run that
// omitted them would not be a preview.
func TestTheDryRunPlanCarriesTheSameManualStepsAsTheInstall(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	plan := BuildPlan(mustDetect(t, root), "dev", Options{})
	if len(plan.Manual) == 0 {
		t.Fatal("want the outstanding steps in the plan")
	}

	out := &strings.Builder{}
	if err := plan.Write(out); err != nil {
		t.Fatal(err)
	}
	for _, step := range plan.Manual {
		if !strings.Contains(out.String(), step) {
			t.Errorf("the plan does not print %q:\n%s", step, out.String())
		}
	}

	report, err := Install(plan, "dev")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(report.Manual, "\n") != strings.Join(plan.Manual, "\n") {
		t.Errorf("plan says %v, report says %v", plan.Manual, report.Manual)
	}
}

// Everything interpolated into the generated YAML is repository content or derived
// from it. A bare interpolation makes a directory called `a: b` into a mapping and
// truncates a remote containing `#` at a comment, producing a config the tool
// cannot read back.
func TestGeneratedFilesSurviveHostileRepositoryContent(t *testing.T) {
	base := t.TempDir()
	root := filepath.Join(base, "repo")
	write(t, root, "package.json", `{"name":"root","workspaces":["packages/*"],"devDependencies":{"typescript":"^5"}}`)
	write(t, root, "tsconfig.json", `{}`)
	write(t, root, "packages/a: b/package.json", `{"name":"weird"}`)
	write(t, root, `packages/quote"and#hash/package.json`, `{"name":"weirder"}`)
	git := testfixture.Git(t, root)
	git("init", "-q", "-b", "main")
	git("remote", "add", "origin", `https://github.com/own#er/na"me.git`)

	install(t, root)

	cfg, _, err := config.Resolve(root, "", func(string) string { return "" })
	if err != nil {
		t.Fatalf("the tool cannot read back the config it generated: %v", err)
	}
	if got := strings.Join(cfg.Projects, "|"); got != `packages/a: b|packages/quote"and#hash` {
		t.Errorf("projects round-tripped as %q", got)
	}
	if cfg.GitHub.Repo != `own#er/na"me` {
		t.Errorf("repo round-tripped as %q", cfg.GitHub.Repo)
	}
}

func TestDurationString(t *testing.T) {
	for _, tc := range []struct {
		in   time.Duration
		want string
	}{
		{2 * time.Minute, "2m"},
		{90 * time.Second, "1m30s"},
		{30 * time.Second, "30s"},
		{time.Hour, "1h"},
		{time.Hour + 30*time.Minute, "1h30m"},
		{70 * time.Second, "1m10s"},
	} {
		if got := durationString(tc.in); got != tc.want {
			t.Errorf("durationString(%v) = %q, want %q", tc.in, got, tc.want)
		}
	}
}
