// SPDX-License-Identifier: MIT

package installer

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/adamtait/reviewer/internal/config"
	"github.com/adamtait/reviewer/internal/testfixture"
)

const releaseV = "v0.1.0"

func TestInstallWritesTheFileSetAndIsIdempotent(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	git := testfixture.Git(t, root)

	first := install(t, root)
	if len(first.Created) != 5 || len(first.Overwritten) != 0 || len(first.Unchanged) != 0 {
		t.Fatalf("want five files created, got %+v", first)
	}
	if status := git("status", "--porcelain"); strings.Count(status, "\n") != 4 {
		// Four untracked lines: .env.example, .github/, .review/ — git collapses
		// new directories — plus nothing else. Anything more is a file the plan
		// did not name.
		t.Logf("status after install:\n%s", status)
	}

	second := install(t, root)
	if len(second.Created) != 0 || len(second.Unchanged) != 5 {
		t.Errorf("a second install must change nothing, got %+v", second)
	}
	if len(second.Manual) == 0 {
		// The devDependency step is still outstanding on a re-run: the installer
		// does not write it, so it cannot know it has been done.
		t.Error("want the outstanding manual steps repeated")
	}
}

// The generated config has to satisfy the loader that will read it, including
// its rejection of unknown keys. A template that drifts from the schema produces
// an install that only fails on the first real review.
func TestTheGeneratedConfigLoadsAndValidates(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	install(t, root)

	cfg, _, err := config.Resolve(root, "", func(string) string { return "" })
	if err != nil {
		t.Fatalf("the generated config does not load: %v", err)
	}
	if err := cfg.Validate(); err != nil {
		t.Fatalf("the generated config does not validate: %v", err)
	}

	if len(cfg.Plugins) != 1 || cfg.Plugins[0].ID != "typescript" {
		t.Fatalf("want the TypeScript plugin configured, got %+v", cfg.Plugins)
	}
	// dist/main.js is the executable; dist/serve.js is the library the package's
	// "main" field names. Pointing at the library gives a process that exits 0
	// without answering the handshake, and a review that reports no analyzers.
	if got := strings.Join(cfg.Plugins[0].Args, " "); !strings.HasSuffix(got, "/dist/main.js") {
		t.Errorf("want the plugin's executable entry point, got %q", got)
	}
	if cfg.LaneB.Enabled {
		t.Error("the model lane must be off in every generated config")
	}
	if cfg.GitHub.ResolveStaleThreads {
		t.Error("resolving a human's thread must be opt-in")
	}
}

func TestTheGeneratedConfigForARepositoryWithoutTypeScript(t *testing.T) {
	root := t.TempDir()
	write(t, root, "package.json", `{"name":"plain"}`)
	testfixture.Git(t, root)("init", "-q", "-b", "main")

	report := install(t, root)
	if len(report.Created) != 5 {
		t.Fatalf("want the full file set regardless, got %+v", report)
	}
	cfg, _, err := config.Resolve(root, "", func(string) string { return "" })
	if err != nil {
		t.Fatalf("the generated config does not load: %v", err)
	}
	if len(cfg.Plugins) != 0 {
		t.Errorf("nothing TypeScript-shaped was detected; got %+v", cfg.Plugins)
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("a plugin-less config must still be valid: %v", err)
	}
	if len(report.Manual) == 0 || strings.Contains(strings.Join(report.Manual, " "), PluginPackage) {
		t.Errorf("want no plugin install step, got %v", report.Manual)
	}
}

func TestForceReplacesAnExistingFile(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	write(t, root, ".review/config.yaml", "plugins: []\n")

	plan := BuildPlan(mustDetect(t, root), releaseV, true)
	report, err := Install(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Overwritten) != 1 || report.Overwritten[0] != ".review/config.yaml" {
		t.Fatalf("want exactly the one existing file replaced, got %+v", report)
	}
	body := read(t, root, ".review/config.yaml")
	if !strings.Contains(body, "Generated by `reviewer init`") {
		t.Error("want the file actually replaced")
	}
}

func TestWithoutForceAnExistingFileIsUntouched(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	write(t, root, ".review/config.yaml", "# mine\nplugins: []\n")

	report := install(t, root)
	if len(report.Unchanged) != 1 {
		t.Fatalf("want the existing file left alone, got %+v", report)
	}
	if body := read(t, root, ".review/config.yaml"); body != "# mine\nplugins: []\n" {
		t.Errorf("the file was modified: %q", body)
	}
}

// The installer must be incapable of persisting a credential. This is a property
// of the templates, so it is asserted against what was actually written rather
// than against the code that writes it.
func TestNothingWrittenLooksLikeACredential(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	report := install(t, root)

	// Any assignment with a non-empty right-hand side in .env.example, plus the
	// key prefixes the providers use.
	assigned := regexp.MustCompile(`(?m)^[A-Z_]+=\S`)
	secretish := regexp.MustCompile(`(sk-|ghp_|github_pat_|gsk_|AIza|xoxb-)`)

	for _, path := range report.Created {
		body := read(t, root, path)
		if path == ".env.example" && assigned.MatchString(body) {
			t.Errorf(".env.example assigns a value:\n%s", body)
		}
		if secretish.MatchString(body) {
			t.Errorf("%s contains something credential-shaped:\n%s", path, body)
		}
	}
}

func TestTheGeneratedWorkflowUsesTheDetectedPackageManager(t *testing.T) {
	for _, tc := range []struct{ lockfile, cache, install string }{
		{"package-lock.json", "cache: npm", "run: npm ci"},
		{"pnpm-lock.yaml", "cache: pnpm", "run: pnpm install --frozen-lockfile"},
		{"yarn.lock", "cache: yarn", "run: yarn install --immutable"},
	} {
		t.Run(tc.lockfile, func(t *testing.T) {
			root := t.TempDir()
			write(t, root, "package.json", `{"name":"x","devDependencies":{"typescript":"^5"}}`)
			write(t, root, "tsconfig.json", `{}`)
			write(t, root, tc.lockfile, "")

			install(t, root)
			body := read(t, root, ".github/workflows/review.yml")
			for _, want := range []string{tc.cache, tc.install} {
				if !strings.Contains(body, want) {
					t.Errorf("want %q in the workflow:\n%s", want, body)
				}
			}
		})
	}
}

// A workflow generated by a release pins that release. One generated by a
// development build cannot, because there is no release archive to download, so it
// carries an obvious placeholder and says so as an outstanding step.
func TestTheGeneratedWorkflowPinsAReleaseOrSaysItCannot(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	plan := BuildPlan(mustDetect(t, root), releaseV, false)
	if _, err := Install(plan, releaseV); err != nil {
		t.Fatal(err)
	}
	if body := read(t, root, ".github/workflows/review.yml"); !strings.Contains(body, "adamtait/reviewer@v0.1.0") {
		t.Errorf("want the release pinned:\n%s", body)
	}

	dev := testfixture.Destination(t, "tiny-monorepo")
	devPlan := BuildPlan(mustDetect(t, dev), "dev", false)
	report, err := Install(devPlan, "dev")
	if err != nil {
		t.Fatal(err)
	}
	body := read(t, dev, ".github/workflows/review.yml")
	if !strings.Contains(body, versionPlaceholder) {
		t.Errorf("want an obvious placeholder, not @vdev:\n%s", body)
	}
	if !strings.Contains(strings.Join(report.Manual, "\n"), versionPlaceholder) {
		t.Errorf("want the placeholder named as an outstanding step, got %v", report.Manual)
	}
}

func TestInstallCommandFollowsThePackageManager(t *testing.T) {
	d := Dependency{Name: PluginPackage, Version: "0.1.0"}
	for manager, want := range map[string]string{
		"npm":     "npm install --save-dev",
		"pnpm":    "pnpm add -Dw",
		"yarn":    "yarn add -D",
		"bun":     "bun add -d",
		"":        "npm install --save-dev",
		"nonsuch": "npm install --save-dev",
	} {
		if got := installCommand(manager, d); !strings.HasPrefix(got, want) {
			t.Errorf("installCommand(%q) = %q, want it to start with %q", manager, got, want)
		}
	}
}

// Render produces content for exactly the files the plan names. A writer that can
// invent a path makes --dry-run's file list a guess.
func TestRenderProducesOnlyPlannedFiles(t *testing.T) {
	root := testfixture.Destination(t, "tiny-monorepo")
	plan := BuildPlan(mustDetect(t, root), releaseV, false)

	files, err := Render(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	planned := map[string]bool{}
	for _, f := range plan.Files {
		planned[f.Path] = true
	}
	for _, f := range files {
		if !planned[f.Path] {
			t.Errorf("rendered %s, which the plan does not name", f.Path)
		}
	}
	if len(files) != len(plan.Files) {
		t.Errorf("rendered %d files for a plan of %d", len(files), len(plan.Files))
	}
}

func install(t *testing.T, root string) Report {
	t.Helper()
	plan := BuildPlan(mustDetect(t, root), releaseV, false)
	report, err := Install(plan, releaseV)
	if err != nil {
		t.Fatal(err)
	}
	return report
}

func read(t *testing.T, root, path string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		t.Fatal(err)
	}
	return string(body)
}
